
[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.10"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.11.0"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "1.0.2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/tucnak/telebot.v2"

[prune]
  go-tests = true
  unused-packages = true
